### ISSUE TITLE
how to install payment font by bower?

### ISSUE THREAD

**Issue by hyzhak** [vendocrat/PaymentFont#31]
Hello, I can't find paymentfont with bower

```
> bower search paymentfont
```

returns 

```
No results.
```

**Comment by rstacruz** [comment]
I tried to the liberty of registering this myself:

    bower register paymentfont git://github.com/vendocrat/PaymentFont.git

But it seems there's an error in [bower.json](https://github.com/vendocrat/PaymentFont/blob/v1.0.0/bower.json) for v1.0.0.

**Comment by AlexanderPoellmann** [comment]
Yep, that error in bower.json was fixed in a pull request, but we obviousloy forgot to register it. Works for me so far now! Is it working for you @Hyzhak?

**Comment by marcokernler** [comment]
Doesn't work for me either:

```bash
$ bower search paymentfont
No results.
```

I tried also to register the plugin, but it seems there's still an error in bower.json

```bash
$ bower register paymentfont git://github.com/vendocrat/PaymentFont.git
bower paymentfont#*            resolve git://github.com/vendocrat/PaymentFont.git#*
bower paymentfont#*           download https://github.com/vendocrat/PaymentFont/archive/v1.0.0.tar.gz
bower paymentfont#*            extract archive.tar.gz
bower paymentfont#*         EMALFORMED Failed to read /var/folders/vq/n_nb9nf57d1b1zxb1m0f_0580000gn/T/marcokernler/bower/paymentfont-39496-hulmU9/bower.json

Additional error details:
Unexpected token ]
```

**Comment by T1st3** [comment]
Hi there,
I also tried to register and got the same error, and I think I spotted the problem.

When browsing the source for release 1.0.0, there is an error (an eol comma) in bower.json:
https://github.com/vendocrat/PaymentFont/blob/v1.0.0/bower.json#L9

Bower works with git tags.
Meaning: although this comma has been fixed, the `bower register` command will try to register the files as they were on tag 1.0.0, and then will get an errored bower.json.

To solve this, the project should be patched and then have an new tag, say 1.0.1.

Only after that, we can try again the `bower register` command.

**Comment by tomsommer** [comment]
Please tag 1.0.1

**Comment by T1st3** [comment]
+1
@AlexanderPoellmann

**Comment by rstacruz** [comment]
pleeeasse just tag it

**Comment by AlexanderPoellmann** [comment]
I'm sorry guys, I've been busy with family and work. PaymentFont v1.1.0 should now be available via Bower too!
